// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKillCriterion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['appapi']['API']['AddKillCriterion'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelMessage() {
  return window['go']['appapi']['API']['CancelMessage']();
}

export function CreateConversation(arg1) {
  return window['go']['appapi']['API']['CreateConversation'](arg1);
}

export function CreateIdea(arg1, arg2, arg3, arg4) {
  return window['go']['appapi']['API']['CreateIdea'](arg1, arg2, arg3, arg4);
}

export function CreateLibraryItem(arg1) {
  return window['go']['appapi']['API']['CreateLibraryItem'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['appapi']['API']['DeleteConversation'](arg1);
}

export function DeleteIdea(arg1) {
  return window['go']['appapi']['API']['DeleteIdea'](arg1);
}

export function DeleteKillCriterion(arg1) {
  return window['go']['appapi']['API']['DeleteKillCriterion'](arg1);
}

export function DeleteLibraryItem(arg1) {
  return window['go']['appapi']['API']['DeleteLibraryItem'](arg1);
}

export function EnsureIndexed(arg1) {
  return window['go']['appapi']['API']['EnsureIndexed'](arg1);
}

export function GetActiveItems(arg1) {
  return window['go']['appapi']['API']['GetActiveItems'](arg1);
}

export function GetConversationDisplayEvents(arg1) {
  return window['go']['appapi']['API']['GetConversationDisplayEvents'](arg1);
}

export function GetConversationScope(arg1) {
  return window['go']['appapi']['API']['GetConversationScope'](arg1);
}

export function GetIdea(arg1) {
  return window['go']['appapi']['API']['GetIdea'](arg1);
}

export function GetRetrievalMode(arg1) {
  return window['go']['appapi']['API']['GetRetrievalMode'](arg1);
}

export function ListBooks() {
  return window['go']['appapi']['API']['ListBooks']();
}

export function ListConversations() {
  return window['go']['appapi']['API']['ListConversations']();
}

export function ListIdeas() {
  return window['go']['appapi']['API']['ListIdeas']();
}

export function ListKillCriteria(arg1) {
  return window['go']['appapi']['API']['ListKillCriteria'](arg1);
}

export function ListLibraryItems() {
  return window['go']['appapi']['API']['ListLibraryItems']();
}

export function ListMessages(arg1) {
  return window['go']['appapi']['API']['ListMessages'](arg1);
}

export function ListReviewsDue() {
  return window['go']['appapi']['API']['ListReviewsDue']();
}

export function ListStatusHistory(arg1) {
  return window['go']['appapi']['API']['ListStatusHistory'](arg1);
}

export function Models() {
  return window['go']['appapi']['API']['Models']();
}

export function Personas() {
  return window['go']['appapi']['API']['Personas']();
}

export function ReadLibraryItem(arg1) {
  return window['go']['appapi']['API']['ReadLibraryItem'](arg1);
}

export function SaveLibraryItem(arg1, arg2) {
  return window['go']['appapi']['API']['SaveLibraryItem'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['appapi']['API']['SendMessage'](arg1, arg2, arg3);
}

export function SetActiveItems(arg1, arg2) {
  return window['go']['appapi']['API']['SetActiveItems'](arg1, arg2);
}

export function SetConversationPersona(arg1, arg2) {
  return window['go']['appapi']['API']['SetConversationPersona'](arg1, arg2);
}

export function SetConversationScope(arg1, arg2) {
  return window['go']['appapi']['API']['SetConversationScope'](arg1, arg2);
}

export function SetIdeaStatus(arg1, arg2, arg3) {
  return window['go']['appapi']['API']['SetIdeaStatus'](arg1, arg2, arg3);
}

export function SetRetrievalMode(arg1, arg2) {
  return window['go']['appapi']['API']['SetRetrievalMode'](arg1, arg2);
}

export function StartupIssues() {
  return window['go']['appapi']['API']['StartupIssues']();
}

export function UpdateIdea(arg1) {
  return window['go']['appapi']['API']['UpdateIdea'](arg1);
}

export function UpdateKillCriterion(arg1) {
  return window['go']['appapi']['API']['UpdateKillCriterion'](arg1);
}
