// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {textbooks} from '../models';
import {provider} from '../models';

export function CreateConversation(arg1:string):Promise<store.Conversation>;

export function CreatePreset(arg1:string,arg2:string):Promise<store.Preset>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeletePreset(arg1:string):Promise<void>;

export function GetConversationScope(arg1:string):Promise<Array<store.TextbookScope>>;

export function ListBooks():Promise<Array<textbooks.Book>>;

export function ListConversations():Promise<Array<store.Conversation>>;

export function ListMessages(arg1:string):Promise<Array<store.Message>>;

export function ListPresets():Promise<Array<store.Preset>>;

export function Models():Promise<Array<provider.ModelInfo>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetConversationMeta(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetConversationScope(arg1:string,arg2:Array<store.TextbookScope>):Promise<void>;

export function StartupIssues():Promise<Array<string>>;

export function UpdatePreset(arg1:string,arg2:string,arg3:string):Promise<void>;
