// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelMessage() {
  return window['go']['appapi']['API']['CancelMessage']();
}

export function CreateConversation(arg1) {
  return window['go']['appapi']['API']['CreateConversation'](arg1);
}

export function CreatePreset(arg1, arg2) {
  return window['go']['appapi']['API']['CreatePreset'](arg1, arg2);
}

export function DeleteConversation(arg1) {
  return window['go']['appapi']['API']['DeleteConversation'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['appapi']['API']['DeletePreset'](arg1);
}

export function EnsureIndexed(arg1) {
  return window['go']['appapi']['API']['EnsureIndexed'](arg1);
}

export function GetConversationScope(arg1) {
  return window['go']['appapi']['API']['GetConversationScope'](arg1);
}

export function ListBooks() {
  return window['go']['appapi']['API']['ListBooks']();
}

export function ListConversations() {
  return window['go']['appapi']['API']['ListConversations']();
}

export function ListMessages(arg1) {
  return window['go']['appapi']['API']['ListMessages'](arg1);
}

export function ListPresets() {
  return window['go']['appapi']['API']['ListPresets']();
}

export function Models() {
  return window['go']['appapi']['API']['Models']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['appapi']['API']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetConversationMeta(arg1, arg2, arg3) {
  return window['go']['appapi']['API']['SetConversationMeta'](arg1, arg2, arg3);
}

export function SetConversationScope(arg1, arg2) {
  return window['go']['appapi']['API']['SetConversationScope'](arg1, arg2);
}

export function StartupIssues() {
  return window['go']['appapi']['API']['StartupIssues']();
}

export function UpdatePreset(arg1, arg2, arg3) {
  return window['go']['appapi']['API']['UpdatePreset'](arg1, arg2, arg3);
}
