// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {library} from '../models';
import {appapi} from '../models';
import {textbooks} from '../models';
import {pipeline} from '../models';
import {provider} from '../models';

export function AddKillCriterion(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<store.KillCriterion>;

export function CancelAssignment(arg1:string):Promise<void>;

export function CancelMessage():Promise<void>;

export function CreateConversation(arg1:string):Promise<store.Conversation>;

export function CreateIdea(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<store.Idea>;

export function CreateLibraryItem(arg1:string):Promise<library.Item>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteIdea(arg1:string):Promise<void>;

export function DeleteKillCriterion(arg1:string):Promise<void>;

export function DeleteLibraryItem(arg1:string):Promise<void>;

export function EnsureIndexed(arg1:string):Promise<void>;

export function EnsureIndexedScope(arg1:Array<store.TextbookScope>):Promise<void>;

export function GetActiveItems(arg1:string):Promise<Array<string>>;

export function GetAssignment(arg1:string):Promise<store.Assignment>;

export function GetAssignmentLibraryItems(arg1:string):Promise<Array<string>>;

export function GetAssignmentLibraryItemsForDir(arg1:string):Promise<Array<string>>;

export function GetAssignmentScope(arg1:string):Promise<Array<store.TextbookScope>>;

export function GetAssignmentScopeForDir(arg1:string):Promise<Array<store.TextbookScope>>;

export function GetConversationDisplayEvents(arg1:string):Promise<Array<appapi.EventDTO>>;

export function GetConversationScope(arg1:string):Promise<Array<store.TextbookScope>>;

export function GetIdea(arg1:string):Promise<store.Idea>;

export function GetRetrievalMode(arg1:string):Promise<string>;

export function ListAssignmentItems(arg1:string):Promise<Array<store.AssignmentItem>>;

export function ListAssignments():Promise<Array<store.Assignment>>;

export function ListBooks():Promise<Array<textbooks.Book>>;

export function ListConversations():Promise<Array<store.Conversation>>;

export function ListIdeas():Promise<Array<store.Idea>>;

export function ListKillCriteria(arg1:string):Promise<Array<store.KillCriterion>>;

export function ListLibraryItems():Promise<Array<library.Item>>;

export function ListMessages(arg1:string):Promise<Array<store.Message>>;

export function ListReviewsDue():Promise<Array<pipeline.DueReviewView>>;

export function ListStatusHistory(arg1:string):Promise<Array<store.StatusChange>>;

export function Models():Promise<Array<provider.ModelInfo>>;

export function ReadLibraryItem(arg1:string):Promise<string>;

export function RerunAssignmentItem(arg1:string,arg2:number):Promise<string>;

export function SaveLibraryItem(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetActiveItems(arg1:string,arg2:Array<string>):Promise<void>;

export function SetAssignmentLibraryItems(arg1:string,arg2:Array<string>):Promise<void>;

export function SetAssignmentScope(arg1:string,arg2:Array<store.TextbookScope>):Promise<void>;

export function SetConversationMeta(arg1:string,arg2:string):Promise<void>;

export function SetConversationScope(arg1:string,arg2:Array<store.TextbookScope>):Promise<void>;

export function SetIdeaStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRetrievalMode(arg1:string,arg2:string):Promise<void>;

export function SolveAssignment(arg1:string,arg2:Array<store.TextbookScope>,arg3:Array<string>):Promise<string>;

export function StartupIssues():Promise<Array<string>>;

export function UpdateIdea(arg1:store.Idea):Promise<void>;

export function UpdateKillCriterion(arg1:store.KillCriterion):Promise<void>;
