// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAssignment(arg1) {
  return window['go']['appapi']['API']['CancelAssignment'](arg1);
}

export function CancelMessage() {
  return window['go']['appapi']['API']['CancelMessage']();
}

export function CreateConversation(arg1) {
  return window['go']['appapi']['API']['CreateConversation'](arg1);
}

export function CreateLibraryItem(arg1) {
  return window['go']['appapi']['API']['CreateLibraryItem'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['appapi']['API']['DeleteConversation'](arg1);
}

export function DeleteLibraryItem(arg1) {
  return window['go']['appapi']['API']['DeleteLibraryItem'](arg1);
}

export function EnsureIndexed(arg1) {
  return window['go']['appapi']['API']['EnsureIndexed'](arg1);
}

export function EnsureIndexedScope(arg1) {
  return window['go']['appapi']['API']['EnsureIndexedScope'](arg1);
}

export function GetActiveItems(arg1) {
  return window['go']['appapi']['API']['GetActiveItems'](arg1);
}

export function GetAssignment(arg1) {
  return window['go']['appapi']['API']['GetAssignment'](arg1);
}

export function GetAssignmentLibraryItems(arg1) {
  return window['go']['appapi']['API']['GetAssignmentLibraryItems'](arg1);
}

export function GetAssignmentScope(arg1) {
  return window['go']['appapi']['API']['GetAssignmentScope'](arg1);
}

export function GetConversationDisplayEvents(arg1) {
  return window['go']['appapi']['API']['GetConversationDisplayEvents'](arg1);
}

export function GetConversationScope(arg1) {
  return window['go']['appapi']['API']['GetConversationScope'](arg1);
}

export function GetRetrievalMode(arg1) {
  return window['go']['appapi']['API']['GetRetrievalMode'](arg1);
}

export function ListAssignmentItems(arg1) {
  return window['go']['appapi']['API']['ListAssignmentItems'](arg1);
}

export function ListAssignments() {
  return window['go']['appapi']['API']['ListAssignments']();
}

export function ListBooks() {
  return window['go']['appapi']['API']['ListBooks']();
}

export function ListConversations() {
  return window['go']['appapi']['API']['ListConversations']();
}

export function ListLibraryItems() {
  return window['go']['appapi']['API']['ListLibraryItems']();
}

export function ListMessages(arg1) {
  return window['go']['appapi']['API']['ListMessages'](arg1);
}

export function Models() {
  return window['go']['appapi']['API']['Models']();
}

export function ReadLibraryItem(arg1) {
  return window['go']['appapi']['API']['ReadLibraryItem'](arg1);
}

export function RerunAssignmentItem(arg1, arg2) {
  return window['go']['appapi']['API']['RerunAssignmentItem'](arg1, arg2);
}

export function SaveLibraryItem(arg1, arg2) {
  return window['go']['appapi']['API']['SaveLibraryItem'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['appapi']['API']['SendMessage'](arg1, arg2, arg3);
}

export function SetActiveItems(arg1, arg2) {
  return window['go']['appapi']['API']['SetActiveItems'](arg1, arg2);
}

export function SetConversationMeta(arg1, arg2) {
  return window['go']['appapi']['API']['SetConversationMeta'](arg1, arg2);
}

export function SetAssignmentScope(arg1, arg2) {
  return window['go']['appapi']['API']['SetAssignmentScope'](arg1, arg2);
}

export function SetConversationScope(arg1, arg2) {
  return window['go']['appapi']['API']['SetConversationScope'](arg1, arg2);
}

export function SetRetrievalMode(arg1, arg2) {
  return window['go']['appapi']['API']['SetRetrievalMode'](arg1, arg2);
}

export function SetAssignmentLibraryItems(arg1, arg2) {
  return window['go']['appapi']['API']['SetAssignmentLibraryItems'](arg1, arg2);
}

export function SolveAssignment(arg1, arg2, arg3) {
  return window['go']['appapi']['API']['SolveAssignment'](arg1, arg2, arg3);
}

export function StartupIssues() {
  return window['go']['appapi']['API']['StartupIssues']();
}
