// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {library} from '../models';
import {textbooks} from '../models';
import {provider} from '../models';

export function CancelMessage():Promise<void>;

export function CreateConversation(arg1:string):Promise<store.Conversation>;

export function CreateLibraryItem(arg1:string):Promise<library.Item>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteLibraryItem(arg1:string):Promise<void>;

export function EnsureIndexed(arg1:string):Promise<void>;

export function GetActiveItems(arg1:string):Promise<Array<string>>;

export function GetConversationScope(arg1:string):Promise<Array<store.TextbookScope>>;

export function ListBooks():Promise<Array<textbooks.Book>>;

export function ListConversations():Promise<Array<store.Conversation>>;

export function ListLibraryItems():Promise<Array<library.Item>>;

export function ListMessages(arg1:string):Promise<Array<store.Message>>;

export function Models():Promise<Array<provider.ModelInfo>>;

export function ReadLibraryItem(arg1:string):Promise<string>;

export function SaveLibraryItem(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetActiveItems(arg1:string,arg2:Array<string>):Promise<void>;

export function SetConversationMeta(arg1:string,arg2:string):Promise<void>;

export function SetConversationScope(arg1:string,arg2:Array<store.TextbookScope>):Promise<void>;

export function StartupIssues():Promise<Array<string>>;
